### ISSUE TITLE
Miettinen Nurminen weights do not iterate to convergence

### ISSUE THREAD

**Issue by jonjvallejo** [PeteLaud/ratesci#20]
Hi,

I just noticed this in comparing some results to SAS output. The MN weights in the scoreci function appear to only iterate a few times, rather than to convergence. In ratesci:::scoretheta, the risk difference is calculated as

else if (contrast == "RD") {
                  wtx <- (1/n1 + 1/n2)^(-1)
                  p2ds <- sum(wtx * p2d)/sum(wtx)
                  p1ds <- sum(wtx * p1d)/sum(wtx)
                  wty <- ((p1ds * (1 - p1ds)/(p2ds * (1 - p2ds)))/n1 + 
                    1/n2)^(-1)
                  wty[p2ds == 0] <- 0
                  p2ds <- sum(wty * p2d)/sum(wty)
                  p1ds <- sum(wty * p1d)/sum(wty)
                  wt <- ((p1ds * (1 - p1ds)/(p2ds * (1 - p2ds)))/n1 + 
                    1/n2)^(-1)
                  wt[p2ds == 0] <- 0
                }

Here, wt should be updated to convergence. For example

tol <- 1E-8

else if (contrast == "RD") {
  wtx <- (1/n1 + 1/n2)^(-1)
  wtdiff <- 1
  
  while (wtdiff > tol){
    p2ds <- sum(wtx * p2d)/sum(wtx)
    p1ds <- sum(wtx * p1d)/sum(wtx)
    wty <- ((p1ds * (1 - p1ds)/(p2ds * (1 - p2ds)))/n1 + 
              1/n2)^(-1)
    wty[p2ds == 0] <- 0
    wtdiff <- abs(max(wtx - wty))
    wtx <- wty
  }
}

where the user may specify a tolerance tol. Thanks for your consideration, and thanks for the wonderful package!

**Comment by PeteLaud** [comment]
Thanks for the suggestion - sorry I missed this issue as there was no email notification - seems I need to 'watch' my own repo to get notifications for it! 
I'll consider developing this feature in the next version. Slightly lazy on my part, as these weights weren't of primary interest to me, and I read somewhere (I forget where) that they converge quite quickly.
What option are you using in SAS to get these weights by the way? My understanding of the Proc Freq documentation is that the weighted method is doing something entirely different.

**Comment by PeteLaud** [comment]
Fixed now, thanks.
